/********************************************************************************
** Form generated from reading UI file 'listgoods.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LISTGOODS_H
#define UI_LISTGOODS_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ListGoods
{
public:
    QLabel *label;
    QPushButton *pushButton_41;
    QPushButton *pushButton_51;
    QPushButton *pushButton_23;
    QPushButton *btn_2_9;
    QPushButton *pushButton_30;
    QPushButton *pushButton_54;
    QPushButton *pushButton_46;
    QPushButton *pushButton_55;
    QPushButton *pushButton_47;
    QPushButton *btn_1_8;
    QPushButton *btn_1_2;
    QPushButton *btn_2_10;
    QPushButton *pushButton_38;
    QPushButton *pushButton_43;
    QPushButton *pushButton_24;
    QPushButton *btn_1_3;
    QPushButton *pushButton_60;
    QPushButton *pushButton_53;
    QPushButton *btn_2_7;
    QPushButton *btn_1_7;
    QPushButton *pushButton_59;
    QPushButton *pushButton_22;
    QPushButton *pushButton_37;
    QPushButton *pushButton_31;
    QPushButton *pushButton_28;
    QPushButton *pushButton_45;
    QPushButton *btn_2_6;
    QPushButton *pushButton_50;
    QPushButton *pushButton_44;
    QPushButton *pushButton_52;
    QPushButton *pushButton_32;
    QPushButton *btn_1_6;
    QPushButton *btn_1_4;
    QPushButton *btn_2_2;
    QPushButton *btn_2_5;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_39;
    QPushButton *pushButton_48;
    QPushButton *pushButton_36;
    QPushButton *pushButton_29;
    QPushButton *pushButton_42;
    QPushButton *pushButton_21;
    QPushButton *pushButton_57;
    QPushButton *pushButton_56;
    QPushButton *pushButton_25;
    QPushButton *btn_2_3;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_58;
    QPushButton *btn_2_1;
    QPushButton *btn_1_9;
    QPushButton *btn_1_5;
    QPushButton *btn_1_10;
    QPushButton *pushButton_35;
    QPushButton *btn_1_1;
    QGroupBox *groupBox;
    QLineEdit *lne_Info_1;
    QSpinBox *spb_count_1;
    QSpinBox *spb_count_2;
    QLineEdit *lne_Info_2;
    QSpinBox *spb_count_3;
    QLineEdit *lne_Info_3;
    QSpinBox *spb_count_4;
    QLineEdit *lne_Info_4;
    QPushButton *pushButton_61;
    QPushButton *pushButton_62;
    QLineEdit *lne_Price_1;
    QLineEdit *lne_Price_2;
    QLineEdit *lne_Price_3;
    QLineEdit *lne_Price_4;
    QLineEdit *lne_Total;
    QLabel *label_2;
    QPushButton *btn_2_4;
    QPushButton *pushButton_40;
    QPushButton *pushButton_49;
    QPushButton *btn_2_8;
    QLabel *label_3;

    void setupUi(QWidget *ListGoods)
    {
        if (ListGoods->objectName().isEmpty())
            ListGoods->setObjectName(QString::fromUtf8("ListGoods"));
        ListGoods->resize(844, 459);
        label = new QLabel(ListGoods);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(-10, 0, 541, 451));
        label->setAcceptDrops(false);
        label->setFrameShape(QFrame::NoFrame);
        label->setPixmap(QPixmap(QString::fromUtf8("../img/MicrosoftTeams-image.png")));
        label->setScaledContents(true);
        pushButton_41 = new QPushButton(ListGoods);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(20, 260, 38, 48));
        QIcon icon;
        icon.addFile(QString::fromUtf8("E:/Images/c2.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_41->setIcon(icon);
        pushButton_41->setIconSize(QSize(40, 40));
        pushButton_51 = new QPushButton(ListGoods);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(20, 320, 38, 48));
        pushButton_51->setIcon(icon);
        pushButton_51->setIconSize(QSize(40, 40));
        pushButton_23 = new QPushButton(ListGoods);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(370, 150, 38, 48));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("E:/Images/Sting.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_23->setIcon(icon1);
        pushButton_23->setIconSize(QSize(40, 40));
        btn_2_9 = new QPushButton(ListGoods);
        btn_2_9->setObjectName(QString::fromUtf8("btn_2_9"));
        btn_2_9->setGeometry(QRect(420, 90, 38, 48));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("E:/Images/pepsi.png"), QSize(), QIcon::Normal, QIcon::Off);
        btn_2_9->setIcon(icon2);
        btn_2_9->setIconSize(QSize(40, 40));
        pushButton_30 = new QPushButton(ListGoods);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(70, 150, 38, 48));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("E:/Images/coca.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_30->setIcon(icon3);
        pushButton_30->setIconSize(QSize(40, 40));
        pushButton_54 = new QPushButton(ListGoods);
        pushButton_54->setObjectName(QString::fromUtf8("pushButton_54"));
        pushButton_54->setGeometry(QRect(220, 320, 38, 48));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8("E:/Images/olong.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_54->setIcon(icon4);
        pushButton_54->setIconSize(QSize(40, 40));
        pushButton_46 = new QPushButton(ListGoods);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(270, 260, 38, 48));
        pushButton_46->setIcon(icon);
        pushButton_46->setIconSize(QSize(40, 40));
        pushButton_55 = new QPushButton(ListGoods);
        pushButton_55->setObjectName(QString::fromUtf8("pushButton_55"));
        pushButton_55->setGeometry(QRect(120, 320, 38, 48));
        pushButton_55->setIcon(icon);
        pushButton_55->setIconSize(QSize(40, 40));
        pushButton_47 = new QPushButton(ListGoods);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(420, 260, 38, 48));
        pushButton_47->setIcon(icon2);
        pushButton_47->setIconSize(QSize(40, 40));
        btn_1_8 = new QPushButton(ListGoods);
        btn_1_8->setObjectName(QString::fromUtf8("btn_1_8"));
        btn_1_8->setGeometry(QRect(370, 30, 38, 48));
        btn_1_8->setIcon(icon1);
        btn_1_8->setIconSize(QSize(40, 40));
        btn_1_2 = new QPushButton(ListGoods);
        btn_1_2->setObjectName(QString::fromUtf8("btn_1_2"));
        btn_1_2->setGeometry(QRect(70, 30, 38, 48));
        btn_1_2->setIconSize(QSize(40, 40));
        btn_1_2->setCheckable(true);
        btn_2_10 = new QPushButton(ListGoods);
        btn_2_10->setObjectName(QString::fromUtf8("btn_2_10"));
        btn_2_10->setGeometry(QRect(470, 90, 38, 48));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8("E:/Images/snackkhoaitay.png"), QSize(), QIcon::Normal, QIcon::Off);
        btn_2_10->setIcon(icon5);
        btn_2_10->setIconSize(QSize(40, 40));
        pushButton_38 = new QPushButton(ListGoods);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(170, 200, 38, 48));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8("E:/Images/coffe.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_38->setIcon(icon6);
        pushButton_38->setIconSize(QSize(40, 40));
        pushButton_43 = new QPushButton(ListGoods);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(370, 260, 38, 48));
        pushButton_43->setIcon(icon1);
        pushButton_43->setIconSize(QSize(40, 40));
        pushButton_24 = new QPushButton(ListGoods);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(220, 150, 38, 48));
        pushButton_24->setIcon(icon4);
        pushButton_24->setIconSize(QSize(40, 40));
        btn_1_3 = new QPushButton(ListGoods);
        btn_1_3->setObjectName(QString::fromUtf8("btn_1_3"));
        btn_1_3->setGeometry(QRect(120, 30, 38, 48));
        btn_1_3->setIconSize(QSize(40, 40));
        btn_1_3->setCheckable(true);
        pushButton_60 = new QPushButton(ListGoods);
        pushButton_60->setObjectName(QString::fromUtf8("pushButton_60"));
        pushButton_60->setGeometry(QRect(70, 320, 38, 48));
        pushButton_60->setIcon(icon3);
        pushButton_60->setIconSize(QSize(40, 40));
        pushButton_53 = new QPushButton(ListGoods);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(370, 320, 38, 48));
        pushButton_53->setIcon(icon1);
        pushButton_53->setIconSize(QSize(40, 40));
        btn_2_7 = new QPushButton(ListGoods);
        btn_2_7->setObjectName(QString::fromUtf8("btn_2_7"));
        btn_2_7->setGeometry(QRect(320, 90, 38, 48));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8("E:/Images/olongkhduong.png"), QSize(), QIcon::Normal, QIcon::Off);
        btn_2_7->setIcon(icon7);
        btn_2_7->setIconSize(QSize(40, 40));
        btn_1_7 = new QPushButton(ListGoods);
        btn_1_7->setObjectName(QString::fromUtf8("btn_1_7"));
        btn_1_7->setGeometry(QRect(320, 30, 38, 48));
        btn_1_7->setIcon(icon7);
        btn_1_7->setIconSize(QSize(40, 40));
        pushButton_59 = new QPushButton(ListGoods);
        pushButton_59->setObjectName(QString::fromUtf8("pushButton_59"));
        pushButton_59->setGeometry(QRect(320, 320, 38, 48));
        pushButton_59->setIcon(icon7);
        pushButton_59->setIconSize(QSize(40, 40));
        pushButton_22 = new QPushButton(ListGoods);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(470, 150, 38, 48));
        pushButton_22->setIcon(icon5);
        pushButton_22->setIconSize(QSize(40, 40));
        pushButton_37 = new QPushButton(ListGoods);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(420, 200, 38, 48));
        pushButton_37->setIcon(icon2);
        pushButton_37->setIconSize(QSize(40, 40));
        pushButton_31 = new QPushButton(ListGoods);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(20, 200, 38, 48));
        pushButton_31->setIcon(icon);
        pushButton_31->setIconSize(QSize(40, 40));
        pushButton_28 = new QPushButton(ListGoods);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(170, 150, 38, 48));
        pushButton_28->setIcon(icon6);
        pushButton_28->setIconSize(QSize(40, 40));
        pushButton_45 = new QPushButton(ListGoods);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(120, 260, 38, 48));
        pushButton_45->setIcon(icon);
        pushButton_45->setIconSize(QSize(40, 40));
        btn_2_6 = new QPushButton(ListGoods);
        btn_2_6->setObjectName(QString::fromUtf8("btn_2_6"));
        btn_2_6->setGeometry(QRect(270, 90, 38, 48));
        btn_2_6->setIcon(icon);
        btn_2_6->setIconSize(QSize(40, 40));
        pushButton_50 = new QPushButton(ListGoods);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(70, 260, 38, 48));
        pushButton_50->setIcon(icon3);
        pushButton_50->setIconSize(QSize(40, 40));
        pushButton_44 = new QPushButton(ListGoods);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(220, 260, 38, 48));
        pushButton_44->setIcon(icon4);
        pushButton_44->setIconSize(QSize(40, 40));
        pushButton_52 = new QPushButton(ListGoods);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(470, 320, 38, 48));
        pushButton_52->setIcon(icon5);
        pushButton_52->setIconSize(QSize(40, 40));
        pushButton_32 = new QPushButton(ListGoods);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(470, 200, 38, 48));
        pushButton_32->setIcon(icon5);
        pushButton_32->setIconSize(QSize(40, 40));
        btn_1_6 = new QPushButton(ListGoods);
        btn_1_6->setObjectName(QString::fromUtf8("btn_1_6"));
        btn_1_6->setGeometry(QRect(270, 30, 38, 48));
        btn_1_6->setIcon(icon);
        btn_1_6->setIconSize(QSize(40, 40));
        btn_1_4 = new QPushButton(ListGoods);
        btn_1_4->setObjectName(QString::fromUtf8("btn_1_4"));
        btn_1_4->setGeometry(QRect(170, 30, 38, 48));
        btn_1_4->setIcon(icon6);
        btn_1_4->setIconSize(QSize(40, 40));
        btn_1_4->setCheckable(true);
        btn_2_2 = new QPushButton(ListGoods);
        btn_2_2->setObjectName(QString::fromUtf8("btn_2_2"));
        btn_2_2->setGeometry(QRect(70, 90, 38, 48));
        btn_2_2->setIcon(icon3);
        btn_2_2->setIconSize(QSize(40, 40));
        btn_2_5 = new QPushButton(ListGoods);
        btn_2_5->setObjectName(QString::fromUtf8("btn_2_5"));
        btn_2_5->setGeometry(QRect(220, 90, 38, 48));
        btn_2_5->setIcon(icon4);
        btn_2_5->setIconSize(QSize(40, 40));
        pushButton_26 = new QPushButton(ListGoods);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(270, 150, 38, 48));
        pushButton_26->setIcon(icon);
        pushButton_26->setIconSize(QSize(40, 40));
        pushButton_27 = new QPushButton(ListGoods);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(420, 150, 38, 48));
        pushButton_27->setIcon(icon2);
        pushButton_27->setIconSize(QSize(40, 40));
        pushButton_39 = new QPushButton(ListGoods);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(320, 200, 38, 48));
        pushButton_39->setIcon(icon7);
        pushButton_39->setIconSize(QSize(40, 40));
        pushButton_48 = new QPushButton(ListGoods);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(170, 260, 38, 48));
        pushButton_48->setIcon(icon6);
        pushButton_48->setIconSize(QSize(40, 40));
        pushButton_36 = new QPushButton(ListGoods);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(270, 200, 38, 48));
        pushButton_36->setIcon(icon);
        pushButton_36->setIconSize(QSize(40, 40));
        pushButton_29 = new QPushButton(ListGoods);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(320, 150, 38, 48));
        pushButton_29->setIcon(icon7);
        pushButton_29->setIconSize(QSize(40, 40));
        pushButton_42 = new QPushButton(ListGoods);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(470, 260, 38, 48));
        pushButton_42->setIcon(icon5);
        pushButton_42->setIconSize(QSize(40, 40));
        pushButton_21 = new QPushButton(ListGoods);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(20, 150, 38, 48));
        pushButton_21->setIcon(icon);
        pushButton_21->setIconSize(QSize(40, 40));
        pushButton_57 = new QPushButton(ListGoods);
        pushButton_57->setObjectName(QString::fromUtf8("pushButton_57"));
        pushButton_57->setGeometry(QRect(420, 320, 38, 48));
        pushButton_57->setIcon(icon2);
        pushButton_57->setIconSize(QSize(40, 40));
        pushButton_56 = new QPushButton(ListGoods);
        pushButton_56->setObjectName(QString::fromUtf8("pushButton_56"));
        pushButton_56->setGeometry(QRect(270, 320, 38, 48));
        pushButton_56->setIcon(icon);
        pushButton_56->setIconSize(QSize(40, 40));
        pushButton_25 = new QPushButton(ListGoods);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(120, 150, 38, 48));
        pushButton_25->setIcon(icon);
        pushButton_25->setIconSize(QSize(40, 40));
        btn_2_3 = new QPushButton(ListGoods);
        btn_2_3->setObjectName(QString::fromUtf8("btn_2_3"));
        btn_2_3->setGeometry(QRect(120, 90, 38, 48));
        btn_2_3->setIcon(icon);
        btn_2_3->setIconSize(QSize(40, 40));
        pushButton_33 = new QPushButton(ListGoods);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(370, 200, 38, 48));
        pushButton_33->setIcon(icon1);
        pushButton_33->setIconSize(QSize(40, 40));
        pushButton_34 = new QPushButton(ListGoods);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(220, 200, 38, 48));
        pushButton_34->setIcon(icon4);
        pushButton_34->setIconSize(QSize(40, 40));
        pushButton_58 = new QPushButton(ListGoods);
        pushButton_58->setObjectName(QString::fromUtf8("pushButton_58"));
        pushButton_58->setGeometry(QRect(170, 320, 38, 48));
        pushButton_58->setIcon(icon6);
        pushButton_58->setIconSize(QSize(40, 40));
        btn_2_1 = new QPushButton(ListGoods);
        btn_2_1->setObjectName(QString::fromUtf8("btn_2_1"));
        btn_2_1->setGeometry(QRect(20, 90, 38, 48));
        btn_2_1->setIcon(icon);
        btn_2_1->setIconSize(QSize(40, 40));
        btn_1_9 = new QPushButton(ListGoods);
        btn_1_9->setObjectName(QString::fromUtf8("btn_1_9"));
        btn_1_9->setGeometry(QRect(420, 30, 38, 48));
        btn_1_9->setIcon(icon2);
        btn_1_9->setIconSize(QSize(40, 40));
        btn_1_5 = new QPushButton(ListGoods);
        btn_1_5->setObjectName(QString::fromUtf8("btn_1_5"));
        btn_1_5->setGeometry(QRect(220, 30, 38, 48));
        btn_1_5->setIcon(icon4);
        btn_1_5->setIconSize(QSize(40, 40));
        btn_1_10 = new QPushButton(ListGoods);
        btn_1_10->setObjectName(QString::fromUtf8("btn_1_10"));
        btn_1_10->setGeometry(QRect(470, 30, 38, 48));
        btn_1_10->setIcon(icon5);
        btn_1_10->setIconSize(QSize(40, 40));
        pushButton_35 = new QPushButton(ListGoods);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(120, 200, 38, 48));
        pushButton_35->setIcon(icon);
        pushButton_35->setIconSize(QSize(40, 40));
        btn_1_1 = new QPushButton(ListGoods);
        btn_1_1->setObjectName(QString::fromUtf8("btn_1_1"));
        btn_1_1->setGeometry(QRect(20, 30, 38, 48));
        btn_1_1->setIconSize(QSize(40, 40));
        btn_1_1->setCheckable(true);
        groupBox = new QGroupBox(ListGoods);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(540, 60, 291, 391));
        QFont font;
        font.setFamily(QString::fromUtf8("DejaVu Sans Mono"));
        font.setPointSize(13);
        font.setBold(true);
        groupBox->setFont(font);
        lne_Info_1 = new QLineEdit(groupBox);
        lne_Info_1->setObjectName(QString::fromUtf8("lne_Info_1"));
        lne_Info_1->setGeometry(QRect(20, 40, 111, 31));
        lne_Info_1->setReadOnly(true);
        spb_count_1 = new QSpinBox(groupBox);
        spb_count_1->setObjectName(QString::fromUtf8("spb_count_1"));
        spb_count_1->setGeometry(QRect(240, 30, 41, 51));
        spb_count_2 = new QSpinBox(groupBox);
        spb_count_2->setObjectName(QString::fromUtf8("spb_count_2"));
        spb_count_2->setGeometry(QRect(240, 100, 41, 51));
        lne_Info_2 = new QLineEdit(groupBox);
        lne_Info_2->setObjectName(QString::fromUtf8("lne_Info_2"));
        lne_Info_2->setGeometry(QRect(20, 110, 111, 31));
        lne_Info_2->setReadOnly(true);
        spb_count_3 = new QSpinBox(groupBox);
        spb_count_3->setObjectName(QString::fromUtf8("spb_count_3"));
        spb_count_3->setGeometry(QRect(240, 170, 41, 51));
        lne_Info_3 = new QLineEdit(groupBox);
        lne_Info_3->setObjectName(QString::fromUtf8("lne_Info_3"));
        lne_Info_3->setGeometry(QRect(20, 180, 111, 31));
        lne_Info_3->setReadOnly(true);
        spb_count_4 = new QSpinBox(groupBox);
        spb_count_4->setObjectName(QString::fromUtf8("spb_count_4"));
        spb_count_4->setGeometry(QRect(240, 240, 41, 51));
        lne_Info_4 = new QLineEdit(groupBox);
        lne_Info_4->setObjectName(QString::fromUtf8("lne_Info_4"));
        lne_Info_4->setGeometry(QRect(20, 250, 111, 31));
        lne_Info_4->setReadOnly(true);
        pushButton_61 = new QPushButton(groupBox);
        pushButton_61->setObjectName(QString::fromUtf8("pushButton_61"));
        pushButton_61->setGeometry(QRect(190, 350, 91, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("DejaVu Sans Mono"));
        font1.setPointSize(14);
        font1.setBold(true);
        pushButton_61->setFont(font1);
        QIcon icon8;
        icon8.addFile(QString::fromUtf8("../icon/Vi_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_61->setIcon(icon8);
        pushButton_61->setIconSize(QSize(40, 30));
        pushButton_62 = new QPushButton(groupBox);
        pushButton_62->setObjectName(QString::fromUtf8("pushButton_62"));
        pushButton_62->setGeometry(QRect(20, 350, 111, 31));
        pushButton_62->setFont(font1);
        QIcon icon9;
        icon9.addFile(QString::fromUtf8("../icon/caychoi_icon.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_62->setIcon(icon9);
        pushButton_62->setIconSize(QSize(30, 25));
        lne_Price_1 = new QLineEdit(groupBox);
        lne_Price_1->setObjectName(QString::fromUtf8("lne_Price_1"));
        lne_Price_1->setGeometry(QRect(140, 40, 91, 31));
        QFont font2;
        font2.setFamily(QString::fromUtf8("DejaVu Sans Mono"));
        font2.setPointSize(9);
        font2.setBold(true);
        lne_Price_1->setFont(font2);
        lne_Price_2 = new QLineEdit(groupBox);
        lne_Price_2->setObjectName(QString::fromUtf8("lne_Price_2"));
        lne_Price_2->setGeometry(QRect(140, 110, 91, 31));
        lne_Price_2->setFont(font2);
        lne_Price_3 = new QLineEdit(groupBox);
        lne_Price_3->setObjectName(QString::fromUtf8("lne_Price_3"));
        lne_Price_3->setGeometry(QRect(140, 180, 91, 31));
        lne_Price_3->setFont(font2);
        lne_Price_4 = new QLineEdit(groupBox);
        lne_Price_4->setObjectName(QString::fromUtf8("lne_Price_4"));
        lne_Price_4->setGeometry(QRect(140, 250, 91, 31));
        lne_Price_4->setFont(font2);
        lne_Total = new QLineEdit(groupBox);
        lne_Total->setObjectName(QString::fromUtf8("lne_Total"));
        lne_Total->setGeometry(QRect(70, 310, 201, 31));
        lne_Total->setReadOnly(true);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 310, 61, 31));
        QFont font3;
        font3.setFamily(QString::fromUtf8("DejaVu Sans Mono"));
        font3.setPointSize(16);
        font3.setBold(true);
        label_2->setFont(font3);
        btn_2_4 = new QPushButton(ListGoods);
        btn_2_4->setObjectName(QString::fromUtf8("btn_2_4"));
        btn_2_4->setGeometry(QRect(170, 90, 38, 48));
        btn_2_4->setIcon(icon6);
        btn_2_4->setIconSize(QSize(40, 40));
        pushButton_40 = new QPushButton(ListGoods);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(70, 200, 38, 48));
        pushButton_40->setIcon(icon3);
        pushButton_40->setIconSize(QSize(40, 40));
        pushButton_49 = new QPushButton(ListGoods);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(320, 260, 38, 48));
        pushButton_49->setIcon(icon7);
        pushButton_49->setIconSize(QSize(40, 40));
        btn_2_8 = new QPushButton(ListGoods);
        btn_2_8->setObjectName(QString::fromUtf8("btn_2_8"));
        btn_2_8->setGeometry(QRect(370, 90, 38, 48));
        btn_2_8->setIcon(icon1);
        btn_2_8->setIconSize(QSize(40, 40));
        label_3 = new QLabel(ListGoods);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(560, 10, 261, 41));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../icon/banvien_logo.png")));
        label_3->setScaledContents(true);

        retranslateUi(ListGoods);

        QMetaObject::connectSlotsByName(ListGoods);
    } // setupUi

    void retranslateUi(QWidget *ListGoods)
    {
        ListGoods->setWindowTitle(QApplication::translate("ListGoods", "List Goods", nullptr));
        label->setText(QString());
        pushButton_41->setText(QString());
        pushButton_51->setText(QString());
        pushButton_23->setText(QString());
        btn_2_9->setText(QString());
        pushButton_30->setText(QString());
        pushButton_54->setText(QString());
        pushButton_46->setText(QString());
        pushButton_55->setText(QString());
        pushButton_47->setText(QString());
        btn_1_8->setText(QString());
        btn_1_2->setText(QString());
        btn_2_10->setText(QString());
        pushButton_38->setText(QString());
        pushButton_43->setText(QString());
        pushButton_24->setText(QString());
        btn_1_3->setText(QString());
        pushButton_60->setText(QString());
        pushButton_53->setText(QString());
        btn_2_7->setText(QString());
        btn_1_7->setText(QString());
        pushButton_59->setText(QString());
        pushButton_22->setText(QString());
        pushButton_37->setText(QString());
        pushButton_31->setText(QString());
        pushButton_28->setText(QString());
        pushButton_45->setText(QString());
        btn_2_6->setText(QString());
        pushButton_50->setText(QString());
        pushButton_44->setText(QString());
        pushButton_52->setText(QString());
        pushButton_32->setText(QString());
        btn_1_6->setText(QString());
        btn_1_4->setText(QString());
        btn_2_2->setText(QString());
        btn_2_5->setText(QString());
        pushButton_26->setText(QString());
        pushButton_27->setText(QString());
        pushButton_39->setText(QString());
        pushButton_48->setText(QString());
        pushButton_36->setText(QString());
        pushButton_29->setText(QString());
        pushButton_42->setText(QString());
        pushButton_21->setText(QString());
        pushButton_57->setText(QString());
        pushButton_56->setText(QString());
        pushButton_25->setText(QString());
        btn_2_3->setText(QString());
        pushButton_33->setText(QString());
        pushButton_34->setText(QString());
        pushButton_58->setText(QString());
        btn_2_1->setText(QString());
        btn_1_9->setText(QString());
        btn_1_5->setText(QString());
        btn_1_10->setText(QString());
        pushButton_35->setText(QString());
        btn_1_1->setText(QString());
        groupBox->setTitle(QApplication::translate("ListGoods", "PAYMENT", nullptr));
        pushButton_61->setText(QApplication::translate("ListGoods", "PAY", nullptr));
        pushButton_62->setText(QApplication::translate("ListGoods", "CLEAR", nullptr));
        label_2->setText(QApplication::translate("ListGoods", "Total", nullptr));
        btn_2_4->setText(QString());
        pushButton_40->setText(QString());
        pushButton_49->setText(QString());
        btn_2_8->setText(QString());
        label_3->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class ListGoods: public Ui_ListGoods {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LISTGOODS_H
